// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdzirueadrtrresdrubb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkemlydWVhZHJ0cnJlc2RydWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjE4MTcsImV4cCI6MjA2MDE5NzgxN30.cf1_DDSAF4P888ih7rh9Ima5u8NwQCybuetb03OF5AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);